### ISSUE TITLE
Load Test Sonuçları Hakkında Medium Yazısı

### ISSUE THREAD

**Issue by tayyiposmanoglu** [Pamir/kubernetes-essentials#3]
Pamir selam,
Son derste istemiş olduğun üzere oluşturmuş olduğumuz ingress controller'lar ile birlikte Azure DevOps üzerinde Load Test yaptım. Sonuçlarını da sana pull request ile ilettim. Bunun hakkında da bir Medium yazısı yazmamı istemiştin. Onu da tamamladım. Yardımların için teşekkür ederim. 

https://medium.com/@osmanoglutayyip.61/azure-devops-load-test-arac%C4%B1l%C4%B1%C4%9F%C4%B1yla-kubernetes-ingress-controller-tipleri-aras%C4%B1nda-performans-11b766f7aa29

**Comment by Pamir** [comment]
@tayyip61 eline saglik super olmus. Pull requeste bir aciklama yazdim. Ona dikkata alarak yaparsan direk publish et.Bir de PR'i ms in reposuna yani https://github.com/msdevengers/kubernetes-essentials yapar misin. Onu bitirdigini ordan publish ederiz.

Eline saglik

**Comment by tayyip61** [comment]
closed
